"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import type { FormEvent } from "react";
import { useAuth } from "@/components/auth-provider";
import { ApiError, apiFetch } from "@/lib/api/client";
import type { BookingDetail, BookingStatus, OperationsStatus, TravelStatus } from "@/types/booking";

interface UserOption { id: string; firstName: string; lastName: string; email: string; isActive: boolean }
const bookingStatuses: BookingStatus[] = ["NEW", "IN_PROGRESS", "READY", "COMPLETED", "CANCELLED"];
const travelStatuses: TravelStatus[] = ["UPCOMING", "IN_TRAVEL", "TRAVEL_COMPLETE", "CANCELLED"];
const operationsStatuses: OperationsStatus[] = ["PENDING", "IN_PROGRESS", "SUPPLIER_PENDING", "TICKETING_PENDING", "READY", "COMPLETE", "ACTION_REQUIRED"];
const inputClass = "mt-1.5 w-full rounded-xl border border-slate-300 px-3 py-2.5 text-sm";

export function BookingWorkspace({ id }: { id: string }) {
  const { hasPermission } = useAuth();
  const [booking, setBooking] = useState<BookingDetail | null>(null);
  const [users, setUsers] = useState<UserOption[]>([]);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [operationsOwnerId, setOperationsOwnerId] = useState("");
  const [passenger, setPassenger] = useState({ firstName: "", lastName: "", dateOfBirth: "", nationality: "", passportNumber: "", passportExpiryDate: "", email: "", phone: "", isPrimaryPassenger: false });
  const [supplier, setSupplier] = useState({ name: "", supplierType: "AIRLINE", serviceType: "", supplierReference: "", supplierCost: "", currency: "GBP", notes: "" });
  const [reference, setReference] = useState({ type: "PNR", reference: "" });
  const [document, setDocument] = useState({ fileName: "", fileType: "application/pdf", storageKey: "", category: "OTHER" });
  const [note, setNote] = useState("");
  const [task, setTask] = useState({ title: "", description: "", assignedUserId: "", dueAt: "" });

  const load = useCallback(async () => {
    try {
      const data = await apiFetch<BookingDetail>(`/bookings/${id}`);
      setBooking(data); setOperationsOwnerId(data.operationsOwner?.id ?? ""); setError("");
      if (hasPermission("user.view")) setUsers((await apiFetch<UserOption[]>("/users")).filter((user) => user.isActive));
    } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to load booking."); }
    finally { setLoading(false); }
  }, [hasPermission, id]);

  useEffect(() => { if (hasPermission("booking.view")) void Promise.resolve().then(load); else void Promise.resolve().then(() => setLoading(false)); }, [hasPermission, load]);
  async function action(path: string, method: "POST" | "PATCH", body?: unknown, success = "Booking updated.") { setSaving(true); setError(""); setMessage(""); try { await apiFetch(path, { method, ...(body !== undefined && { body: JSON.stringify(body) }) }); setMessage(success); await load(); return true; } catch (caught) { setError(caught instanceof ApiError ? caught.message : "Unable to update booking."); return false; } finally { setSaving(false); } }
  async function submit(event: FormEvent, path: string, body: unknown, success: string, reset: () => void) { event.preventDefault(); if (await action(path, "POST", body, success)) reset(); }

  if (!hasPermission("booking.view")) return <div className="p-12 text-amber-800">You do not have permission to view this booking.</div>;
  if (loading) return <div className="p-12 text-center text-slate-500">Loading booking…</div>;
  if (!booking) return <div className="p-12 text-center text-red-700">{error || "Booking not found."}</div>;

  return <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8 lg:py-10">
    <header className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-emerald-700">Booking Folder</p><h1 className="mt-2 text-3xl font-semibold text-slate-950">FOLDER {booking.folderNumber}</h1><p className="mt-2 text-sm text-slate-600">{booking.customer.firstName} {booking.customer.lastName} · {booking.destination}</p></div><Link href="/bookings" className="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-semibold">All bookings</Link></header>
    {message && <div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">{message}</div>}{error && <div className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}

    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-semibold">Overview</h2><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Customer", `${booking.customer.firstName} ${booking.customer.lastName}`], ["Travel", `${new Date(booking.travelStartDate).toLocaleDateString("en-GB")}${booking.travelEndDate ? ` – ${new Date(booking.travelEndDate).toLocaleDateString("en-GB")}` : ""}`], ["Sales Advisor", `${booking.salesAdvisor.firstName} ${booking.salesAdvisor.lastName}`], ["Operations Owner", booking.operationsOwner ? `${booking.operationsOwner.firstName} ${booking.operationsOwner.lastName}` : "Unassigned"], ["Booking", booking.status], ["Travel Status", booking.travelStatus], ["Operations", booking.operationsStatus], ["Accounts", booking.accountsStatus], ["Folder", booking.folderStatus], ["Selling Price", booking.sellingPrice ? `${booking.currency} ${booking.sellingPrice}` : "Restricted"], ["Supplier Cost", booking.supplierCost !== undefined ? `${booking.currency} ${booking.supplierCost ?? "—"}` : "Restricted"]].map(([label, value]) => <div key={label}><dt className="text-xs uppercase text-slate-500">{label}</dt><dd className="mt-1 text-sm font-semibold text-slate-900">{String(value).replaceAll("_", " ")}</dd></div>)}</dl>
      {hasPermission("booking.status.manage") && <div className="mt-6 grid gap-3 border-t border-slate-100 pt-5 sm:grid-cols-3"><label className="text-sm">Booking Status<select value={booking.status} onChange={(e) => void action(`/bookings/${id}/status`, "PATCH", { status: e.target.value }, "Booking status updated.")} className={inputClass}>{bookingStatuses.map((x) => <option key={x}>{x}</option>)}</select></label><label className="text-sm">Operations Status<select value={booking.operationsStatus} onChange={(e) => void action(`/bookings/${id}/operations-status`, "PATCH", { status: e.target.value }, "Operations status updated.")} className={inputClass}>{operationsStatuses.map((x) => <option key={x}>{x}</option>)}</select></label><label className="text-sm">Travel Status<select value={booking.travelStatus} onChange={(e) => void action(`/bookings/${id}/travel-status`, "PATCH", { status: e.target.value }, "Travel status updated.")} className={inputClass}>{travelStatuses.map((x) => <option key={x}>{x}</option>)}</select></label></div>}
      {hasPermission("booking.assign_operations") && <form onSubmit={(e) => void submit(e, `/bookings/${id}/assign-operations`, { userId: operationsOwnerId }, "Operations owner assigned.", () => undefined)} className="mt-5 flex flex-col gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:items-end"><label className="flex-1 text-sm">Operations Owner{users.length ? <select required value={operationsOwnerId} onChange={(e) => setOperationsOwnerId(e.target.value)} className={inputClass}><option value="">Select user</option>{users.map((user) => <option key={user.id} value={user.id}>{user.firstName} {user.lastName}</option>)}</select> : <input required value={operationsOwnerId} onChange={(e) => setOperationsOwnerId(e.target.value)} placeholder="Operations user UUID" className={inputClass}/>}</label><button disabled={saving} className="rounded-xl bg-emerald-700 px-5 py-2.5 text-sm font-semibold text-white">Assign</button></form>}
    </section>

    <div className="mt-6 grid gap-6 xl:grid-cols-2">
      <Section title="Passengers" count={booking.passengers.length}>{booking.passengers.map((p) => <article key={p.id} className="rounded-xl bg-slate-50 p-4"><p className="font-semibold">{p.firstName} {p.lastName}{p.isPrimaryPassenger ? " · Primary" : ""}</p><p className="mt-1 text-sm text-slate-600">{p.nationality ?? "Nationality —"} · Passport {p.passportNumber ?? "—"}</p></article>)}{hasPermission("booking.manage_passengers") && <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold text-emerald-700">Add Passenger</summary><form onSubmit={(e) => void submit(e, `/bookings/${id}/passengers`, { ...passenger, dateOfBirth: passenger.dateOfBirth || undefined, passportExpiryDate: passenger.passportExpiryDate || undefined }, "Passenger added.", () => setPassenger({ firstName: "", lastName: "", dateOfBirth: "", nationality: "", passportNumber: "", passportExpiryDate: "", email: "", phone: "", isPrimaryPassenger: false }))} className="mt-4 grid gap-3 sm:grid-cols-2"><input required placeholder="First name" value={passenger.firstName} onChange={(e) => setPassenger({ ...passenger, firstName: e.target.value })} className={inputClass}/><input required placeholder="Last name" value={passenger.lastName} onChange={(e) => setPassenger({ ...passenger, lastName: e.target.value })} className={inputClass}/><input type="date" value={passenger.dateOfBirth} onChange={(e) => setPassenger({ ...passenger, dateOfBirth: e.target.value })} className={inputClass}/><input placeholder="Nationality" value={passenger.nationality} onChange={(e) => setPassenger({ ...passenger, nationality: e.target.value })} className={inputClass}/><input placeholder="Passport number" value={passenger.passportNumber} onChange={(e) => setPassenger({ ...passenger, passportNumber: e.target.value })} className={inputClass}/><input type="date" value={passenger.passportExpiryDate} onChange={(e) => setPassenger({ ...passenger, passportExpiryDate: e.target.value })} className={inputClass}/><input placeholder="Email" value={passenger.email} onChange={(e) => setPassenger({ ...passenger, email: e.target.value })} className={inputClass}/><input placeholder="Phone" value={passenger.phone} onChange={(e) => setPassenger({ ...passenger, phone: e.target.value })} className={inputClass}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={passenger.isPrimaryPassenger} onChange={(e) => setPassenger({ ...passenger, isPrimaryPassenger: e.target.checked })}/>Primary passenger</label><button className="rounded-xl bg-emerald-700 px-4 py-2.5 text-white">Add Passenger</button></form></details>}</Section>

      <Section title="Suppliers" count={booking.suppliers.length}>{booking.suppliers.map((s) => <article key={s.id} className="rounded-xl bg-slate-50 p-4"><p className="font-semibold">{s.supplier.name} · {s.serviceType}</p><p className="mt-1 text-sm text-slate-600">{s.supplierReference ?? "No reference"} · {s.status.replaceAll("_", " ")}{s.supplierCost !== undefined ? ` · ${s.currency ?? booking.currency} ${s.supplierCost ?? "—"}` : ""}</p></article>)}{hasPermission("booking.manage_suppliers") && <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold text-emerald-700">Add Supplier</summary><form onSubmit={(e) => void submit(e, `/bookings/${id}/suppliers`, { ...supplier, supplierCost: supplier.supplierCost || undefined }, "Supplier added.", () => setSupplier({ name: "", supplierType: "AIRLINE", serviceType: "", supplierReference: "", supplierCost: "", currency: "GBP", notes: "" }))} className="mt-4 grid gap-3 sm:grid-cols-2"><input required placeholder="Supplier name" value={supplier.name} onChange={(e) => setSupplier({ ...supplier, name: e.target.value })} className={inputClass}/><select value={supplier.supplierType} onChange={(e) => setSupplier({ ...supplier, supplierType: e.target.value })} className={inputClass}>{["AIRLINE","HOTEL","TOUR_OPERATOR","TRANSFER","CRUISE","INSURANCE","OTHER"].map((x) => <option key={x}>{x}</option>)}</select><input required placeholder="Service type" value={supplier.serviceType} onChange={(e) => setSupplier({ ...supplier, serviceType: e.target.value })} className={inputClass}/><input placeholder="Supplier reference" value={supplier.supplierReference} onChange={(e) => setSupplier({ ...supplier, supplierReference: e.target.value })} className={inputClass}/>{hasPermission("finance.edit") && <><input type="number" min="0" step="0.01" placeholder="Supplier cost" value={supplier.supplierCost} onChange={(e) => setSupplier({ ...supplier, supplierCost: e.target.value })} className={inputClass}/><input maxLength={3} value={supplier.currency} onChange={(e) => setSupplier({ ...supplier, currency: e.target.value.toUpperCase() })} className={inputClass}/></>}<textarea placeholder="Notes" value={supplier.notes} onChange={(e) => setSupplier({ ...supplier, notes: e.target.value })} className={`${inputClass} sm:col-span-2`}/><button className="rounded-xl bg-emerald-700 px-4 py-2.5 text-white">Add Supplier</button></form></details>}</Section>

      <Section title="References / PNR" count={booking.references.length}>{booking.references.map((r) => <article key={r.id} className="rounded-xl bg-slate-50 p-4"><p className="text-xs uppercase text-slate-500">{r.type.replaceAll("_", " ")}</p><p className="mt-1 font-mono font-semibold">{r.reference}</p></article>)}{hasPermission("booking.manage_references") && <form onSubmit={(e) => void submit(e, `/bookings/${id}/references`, reference, "Reference added.", () => setReference({ type: "PNR", reference: "" }))} className="grid gap-3 sm:grid-cols-[180px_1fr_auto]"><select value={reference.type} onChange={(e) => setReference({ ...reference, type: e.target.value })} className={inputClass}>{["PNR","AIRLINE_REFERENCE","HOTEL_REFERENCE","SUPPLIER_REFERENCE","TICKET_NUMBER","OTHER"].map((x) => <option key={x}>{x}</option>)}</select><input required placeholder="Reference" value={reference.reference} onChange={(e) => setReference({ ...reference, reference: e.target.value })} className={inputClass}/><button className="mt-1.5 rounded-xl bg-emerald-700 px-4 py-2.5 text-white">Add</button></form>}</Section>

      <Section title="Operational Notes" count={booking.notes.length}>{hasPermission("booking.manage_notes") && <form onSubmit={(e) => void submit(e, `/bookings/${id}/notes`, { content: note }, "Note added.", () => setNote(""))} className="flex gap-3"><textarea required value={note} onChange={(e) => setNote(e.target.value)} placeholder="Internal operational note" className={`${inputClass} flex-1`}/><button className="mt-1.5 self-end rounded-xl bg-emerald-700 px-4 py-2.5 text-white">Add</button></form>}{booking.notes.map((n) => <article key={n.id} className="rounded-xl bg-slate-50 p-4"><p className="text-sm">{n.content}</p><p className="mt-2 text-xs text-slate-500">{new Date(n.createdAt).toLocaleString("en-GB")} · {n.createdBy.firstName} {n.createdBy.lastName}</p></article>)}</Section>

      <Section title="Tasks" count={booking.tasks.length}>{booking.tasks.map((t) => <article key={t.id} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><p className="font-semibold">{t.title}</p><span className="text-xs font-bold">{t.status.replaceAll("_", " ")}</span></div><p className="mt-1 text-sm text-slate-600">Due: {t.dueAt ? new Date(t.dueAt).toLocaleString("en-GB") : "—"} · Assigned: {t.assignedUser ? `${t.assignedUser.firstName} ${t.assignedUser.lastName}` : "Unassigned"}</p>{hasPermission("booking.manage_tasks") && t.status !== "COMPLETED" && <button onClick={() => void action(`/bookings/${id}/tasks/${t.id}`, "PATCH", { status: "COMPLETED" }, "Task completed.")} className="mt-2 text-xs font-semibold text-emerald-700">Mark complete</button>}</article>)}{hasPermission("booking.manage_tasks") && <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold text-emerald-700">Create Task</summary><form onSubmit={(e) => void submit(e, `/bookings/${id}/tasks`, { ...task, assignedUserId: task.assignedUserId || undefined, dueAt: task.dueAt ? new Date(task.dueAt).toISOString() : undefined }, "Task created.", () => setTask({ title: "", description: "", assignedUserId: "", dueAt: "" }))} className="mt-4 grid gap-3 sm:grid-cols-2"><input required placeholder="Title" value={task.title} onChange={(e) => setTask({ ...task, title: e.target.value })} className={inputClass}/><input type="datetime-local" value={task.dueAt} onChange={(e) => setTask({ ...task, dueAt: e.target.value })} className={inputClass}/><textarea placeholder="Description" value={task.description} onChange={(e) => setTask({ ...task, description: e.target.value })} className={inputClass}/>{users.length ? <select value={task.assignedUserId} onChange={(e) => setTask({ ...task, assignedUserId: e.target.value })} className={inputClass}><option value="">Unassigned</option>{users.map((u) => <option key={u.id} value={u.id}>{u.firstName} {u.lastName}</option>)}</select> : <input placeholder="Assigned user UUID" value={task.assignedUserId} onChange={(e) => setTask({ ...task, assignedUserId: e.target.value })} className={inputClass}/>}<button className="rounded-xl bg-emerald-700 px-4 py-2.5 text-white">Create Task</button></form></details>}</Section>

      <Section title="Documents" count={booking.documents.length}>{booking.documents.map((d) => <article key={d.id} className="rounded-xl bg-slate-50 p-4"><p className="font-semibold">{d.fileName}</p><p className="mt-1 text-xs text-slate-500">{d.category.replaceAll("_", " ")} · metadata only</p></article>)}{hasPermission("booking.manage_documents") && <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold text-emerald-700">Add Document Metadata</summary><form onSubmit={(e) => void submit(e, `/bookings/${id}/documents`, document, "Document metadata added.", () => setDocument({ fileName: "", fileType: "application/pdf", storageKey: "", category: "OTHER" }))} className="mt-4 grid gap-3 sm:grid-cols-2"><input required placeholder="File name" value={document.fileName} onChange={(e) => setDocument({ ...document, fileName: e.target.value })} className={inputClass}/><input required placeholder="File type" value={document.fileType} onChange={(e) => setDocument({ ...document, fileType: e.target.value })} className={inputClass}/><input required placeholder="Development storage key" value={document.storageKey} onChange={(e) => setDocument({ ...document, storageKey: e.target.value })} className={inputClass}/><select value={document.category} onChange={(e) => setDocument({ ...document, category: e.target.value })} className={inputClass}>{["TICKET","ITINERARY","INVOICE","SUPPLIER_DOCUMENT","PASSENGER_DOCUMENT","OTHER"].map((x) => <option key={x}>{x}</option>)}</select><button className="rounded-xl bg-emerald-700 px-4 py-2.5 text-white">Save Metadata</button></form></details>}</Section>

      <Section title="Activity" count={booking.activity.length}>{booking.activity.map((a) => <article key={a.id} className="border-l-2 border-emerald-200 pl-4"><p className="text-sm font-semibold">{a.action.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-slate-500">{new Date(a.createdAt).toLocaleString("en-GB")} · {a.actor.firstName} {a.actor.lastName}</p></article>)}</Section>
    </div>
  </div>;
}

function Section({ title, count, children }: { title: string; count: number; children: React.ReactNode }) {
  return <section className="space-y-3 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold text-slate-950">{title}</h2><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold text-slate-600">{count}</span></div>{children}</section>;
}
