"use client";
import { useCallback, useEffect, useState } from "react";
import { ApiError, apiFetch } from "@/lib/api/client";
import { useAuth } from "./auth-provider";

type Provider={name:string;status:"NOT_CONFIGURED"|"CONNECTED"|"DEGRADED"|"ERROR"|"DISABLED";isEnabled:boolean;lastCheckedAt:string|null;lastSuccessAt:string|null;lastErrorAt:string|null;lastErrorMessage:string|null};
type Status={wise:Provider;telephony:Provider;website:Provider};
const typeByKey={wise:"WISE",telephony:"TELEPHONY",website:"WEBSITE"} as const;
export function IntegrationStatus(){const {hasPermission}=useAuth();const [data,setData]=useState<Status|null>(null);const [error,setError]=useState("");const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);setError("");try{setData(await apiFetch<Status>("/integrations/status"));}catch(e){setError(e instanceof ApiError?e.message:"Unable to load integration status.");}finally{setLoading(false);}},[]);useEffect(()=>{if(hasPermission("integration.view"))void Promise.resolve().then(load);else void Promise.resolve().then(()=>setLoading(false));},[hasPermission,load]);
 async function toggle(key:keyof Status,value:boolean){setError("");try{await apiFetch(`/integrations/${typeByKey[key]}`,{method:"PATCH",body:JSON.stringify({isEnabled:value})});await load();}catch(e){setError(e instanceof ApiError?e.message:"Unable to update integration.");}}
 if(!hasPermission("integration.view"))return <div className="p-8"><p className="rounded-2xl bg-amber-50 p-6 text-amber-900">You do not have permission to view integrations.</p></div>;
 return <div className="mx-auto max-w-6xl px-5 py-8 sm:px-8"><p className="text-sm font-semibold uppercase tracking-wider text-violet-700">Settings</p><h1 className="mt-1 text-3xl font-semibold">External Integrations</h1><p className="mt-2 text-sm text-slate-600">Safe provider readiness status. Credentials are never returned to this page.</p>{error&&<p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{loading?<p className="mt-7 rounded-2xl border bg-white p-10 text-center text-slate-500">Loading integrations…</p>:data&&<div className="mt-7 grid gap-4 md:grid-cols-3">{(Object.entries(data) as [keyof Status,Provider][]).map(([key,p])=><article key={key} className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-3"><h2 className="font-semibold">{p.name}</h2><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${p.status==="CONNECTED"?"bg-emerald-50 text-emerald-800":p.status==="ERROR"?"bg-red-50 text-red-800":"bg-slate-100 text-slate-700"}`}>{p.status.replaceAll("_"," ")}</span></div><p className="mt-4 text-sm text-slate-600">{key==="wise"?"Payment verification adapter foundation.":key==="telephony"?"Generic PBX calling foundation.":"Secure, idempotent website lead intake."}</p>{p.lastErrorMessage&&<p className="mt-3 text-sm text-red-700">{p.lastErrorMessage}</p>}{hasPermission("integration.manage")&&<button onClick={()=>void toggle(key,!p.isEnabled)} className="mt-5 rounded-lg border px-3 py-2 text-sm font-semibold">{p.isEnabled?"Disable":"Enable"}</button>}</article>)}</div>}</div>}
