"use client";

import Link from "next/link";
import { DragEvent, useCallback, useEffect, useState } from "react";
import { apiFetch } from "@/lib/api/client";
import type { ContentBoard, ContentCard, ContentStage } from "@/types/marketing-content";

const stages=["IDEA","CREATING","REVIEW","READY","LIVE"] as const;

export function MarketingFlowBoard(){const [board,setBoard]=useState<ContentBoard|null>(null);const [search,setSearch]=useState("");const [priority,setPriority]=useState("");const [error,setError]=useState("");const load=useCallback(async()=>{const query=new URLSearchParams();if(search)query.set("search",search);if(priority)query.set("priority",priority);try{setBoard(await apiFetch<ContentBoard>(`/marketing/content/board?${query}`));setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load creative board.")}},[priority,search]);useEffect(()=>{void Promise.resolve().then(load)},[load]);async function move(event:DragEvent,stage:ContentStage){event.preventDefault();const id=event.dataTransfer.getData("content-id");const from=event.dataTransfer.getData("content-stage") as ContentStage;if(!id||from===stage)return;try{if(stage==="REVIEW")await apiFetch(`/marketing/content/${id}/submit-review`,{method:"POST",body:"{}"});else if(stage==="LIVE")await apiFetch(`/marketing/content/${id}/go-live`,{method:"POST",body:"{}"});else await apiFetch(`/marketing/content/${id}/stage`,{method:"PATCH",body:JSON.stringify({stage})});await load()}catch(e){setError(e instanceof Error?e.message:"Move rejected by workflow rules.");await load()}}return <main className="px-5 py-8 sm:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-violet-700">NEO FLOW</p><h1 className="mt-1 text-3xl font-semibold">Creative Content Board</h1><p className="mt-2 text-sm text-slate-600">See content, move work, review creative, approve and publish.</p></div><Link href="/marketing/content/new" className="rounded-xl bg-violet-700 px-5 py-3 font-semibold text-white">Create content</Link></div><div className="mt-6 flex gap-3 rounded-2xl border bg-white p-4"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search content" className="min-w-56 flex-1 rounded-xl border px-4 py-2"/><select value={priority} onChange={e=>setPriority(e.target.value)} className="rounded-xl border px-4 py-2"><option value="">All priorities</option>{["LOW","NORMAL","HIGH","URGENT"].map(x=><option key={x}>{x}</option>)}</select></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<div className="mt-6 grid min-w-[1200px] grid-cols-5 gap-4 overflow-x-auto pb-4">{stages.map(stage=><section key={stage} onDragOver={e=>e.preventDefault()} onDrop={e=>void move(e,stage)} className="min-h-[540px] rounded-2xl bg-slate-100 p-3"><div className="mb-3 flex justify-between px-1"><h2 className="text-sm font-bold">{stage}</h2><span className="rounded-full bg-white px-2 text-xs">{board?.[stage].length??0}</span></div><div className="space-y-3">{board?.[stage].map(item=><ContentCardView key={item.id} item={item}/>)}</div></section>)}</div></main>}

function ContentCardView({item}:{item:ContentCard}){const deadline=deadlineState(item.deadline);return <article draggable onDragStart={e=>{e.dataTransfer.setData("content-id",item.id);e.dataTransfer.setData("content-stage",item.stage)}} className="cursor-grab rounded-xl border bg-white p-4 shadow-sm"><Link href={`/marketing/content/${item.id}`} className="font-semibold text-violet-800">{item.title}</Link><p className="mt-1 text-xs text-slate-500">{item.contentCode} · {item.contentType.replaceAll("_"," ")}</p>{item.reviewRequired&&<p className="mt-3 rounded-lg bg-amber-100 p-2 text-xs font-bold text-amber-900">⚠ DEAL UPDATED<br/>Creative Review Required</p>}<dl className="mt-3 space-y-2 text-xs"><Line label="Assigned" value={item.assignedUser?`${item.assignedUser.firstName} ${item.assignedUser.lastName}`:"Unassigned"}/><Line label="Campaign" value={item.campaign?.name??"—"}/><Line label="Deal" value={item.deal?.dealCode??"—"}/><Line label="Deadline" value={item.deadline?new Date(item.deadline).toLocaleDateString("en-GB"):"—"}/></dl><div className="mt-3 flex justify-between"><span className={`text-xs font-bold ${deadline.color}`}>{deadline.label}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-xs">{item.priority}</span></div></article>}
function Line({label,value}:{label:string;value:string}){return <div><dt className="text-slate-400">{label}</dt><dd>{value}</dd></div>}
function deadlineState(value:string|null){if(!value)return{label:"No deadline",color:"text-slate-400"};const date=new Date(value);const today=new Date();today.setHours(0,0,0,0);const days=Math.round((date.getTime()-today.getTime())/86400000);if(days<0)return{label:"Overdue",color:"text-red-700"};if(days===0)return{label:"Due today",color:"text-orange-700"};if(days<=3)return{label:"Due soon",color:"text-amber-700"};return{label:"Scheduled",color:"text-emerald-700"}}
