"use client";

import Link from "next/link";
import { DragEvent, FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { apiFetch } from "@/lib/api/client";
import type { CalendarEvent, CalendarView, MarketingAlert, MetaStatus } from "@/types/marketing-calendar";

const activityFilters=["ALL","CONTENT","DEAL_EXPIRY","CAMPAIGN","WEBSITE","FACEBOOK","INSTAGRAM","PAID_AD","NEOTRIO"];
const dayMs=86400000;
const pad=(n:number)=>String(n).padStart(2,"0");
const localDate=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const startDay=(d:Date)=>new Date(d.getFullYear(),d.getMonth(),d.getDate());

export function MarketingPlanCalendar(){
  const [view,setView]=useState<CalendarView>("month"); const [cursor,setCursor]=useState(()=>startDay(new Date())); const [events,setEvents]=useState<CalendarEvent[]>([]); const [alerts,setAlerts]=useState<MarketingAlert[]>([]); const [meta,setMeta]=useState<MetaStatus|null>(null); const [activity,setActivity]=useState("ALL"); const [owner,setOwner]=useState(""); const [status,setStatus]=useState(""); const [error,setError]=useState(""); const [showForm,setShowForm]=useState(false);
  useEffect(()=>{const saved=localStorage.getItem("neo-plan-view");if(saved==="day"||saved==="week"||saved==="month")void Promise.resolve().then(()=>setView(saved))},[]);
  const range=useMemo(()=>rangeFor(view,cursor),[view,cursor]);
  const load=useCallback(async()=>{try{const qs=new URLSearchParams({dateFrom:range.from.toISOString(),dateTo:range.to.toISOString()});if(activity!=="ALL")qs.set("entryType",activity);if(owner)qs.set("assignedUserId",owner);if(status)qs.set("status",status);const [items,alertItems,metaStatus]=await Promise.all([apiFetch<CalendarEvent[]>(`/marketing/calendar?${qs}`),apiFetch<MarketingAlert[]>("/marketing/calendar/alerts").catch(()=>[]),apiFetch<MetaStatus>("/integrations/meta/status").catch(()=>null)]);setEvents(items);setAlerts(alertItems);setMeta(metaStatus);setError("")}catch(e){setError(e instanceof Error?e.message:"Unable to load NEO PLAN.")}},[activity,owner,range.from,range.to,status]);
  useEffect(()=>{void Promise.resolve().then(load)},[load]);
  const days=useMemo(()=>daysFor(view,range.from,range.to),[range.from,range.to,view]);
  function changeView(next:CalendarView){setView(next);localStorage.setItem("neo-plan-view",next)}
  function moveCursor(amount:number){const d=new Date(cursor);if(view==="month")d.setMonth(d.getMonth()+amount);else d.setDate(d.getDate()+amount*(view==="week"?7:1));setCursor(d)}
  async function drop(e:DragEvent,date:Date){e.preventDefault();const id=e.dataTransfer.getData("calendar-id");const original=e.dataTransfer.getData("calendar-start");if(!id||!original)return;const old=new Date(original);const next=new Date(date);next.setHours(old.getHours(),old.getMinutes(),old.getSeconds(),0);try{await apiFetch(`/marketing/calendar/${encodeURIComponent(id)}/reschedule`,{method:"PATCH",body:JSON.stringify({startAt:next.toISOString()})});await load()}catch(err){setError(err instanceof Error?err.message:"This event cannot be rescheduled.")}}
  const owners=Array.from(new Set(events.map(x=>x.assignedUserId).filter(Boolean))) as string[];
  return <main className="px-4 py-7 sm:px-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold uppercase tracking-[.22em] text-indigo-700">NEO PLAN</p><h1 className="text-3xl font-semibold">Smart Marketing Calendar</h1><p className="mt-2 text-sm text-slate-600">One view of what is planned, scheduled, live, expiring and missing.</p></div><div className="flex flex-wrap gap-2"><Link className="rounded-lg border bg-white px-3 py-2 text-sm font-semibold" href="/marketing/content/new">Add Content</Link><Link className="rounded-lg border bg-white px-3 py-2 text-sm font-semibold" href="/marketing/content/new">Create Campaign</Link><Link className="rounded-lg border bg-white px-3 py-2 text-sm font-semibold" href="/marketing/deals/new">Launch Deal</Link><button onClick={()=>setShowForm(true)} className="rounded-lg bg-indigo-700 px-3 py-2 text-sm font-semibold text-white">Add Calendar Event</button></div></header>
  <section className="mt-5 grid gap-3 lg:grid-cols-[1fr_auto]"><div className="rounded-2xl border bg-white p-4"><div className="flex flex-wrap gap-2">{activityFilters.map(x=><button key={x} onClick={()=>setActivity(x)} className={`rounded-full px-3 py-1.5 text-xs font-semibold ${activity===x?"bg-indigo-700 text-white":"bg-slate-100 text-slate-700"}`}>{x.replaceAll("_"," ")}</button>)}</div><div className="mt-3 flex flex-wrap gap-3"><select value={owner} onChange={e=>setOwner(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="">All owners</option>{owners.map(x=><option key={x} value={x}>{x.slice(0,8)}…</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="">All statuses</option>{["DRAFT","PLANNED","SCHEDULED","READY","PUBLISHED","COMPLETED","CANCELLED","FAILED"].map(x=><option key={x}>{x}</option>)}</select></div></div><MetaCard meta={meta}/></section>
  {error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}
  <section className="mt-5 rounded-2xl border bg-white p-4 shadow-sm"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex gap-2"><button onClick={()=>moveCursor(-1)} className="rounded-lg border px-3 py-2">←</button><button onClick={()=>setCursor(startDay(new Date()))} className="rounded-lg border px-3 py-2 text-sm">Today</button><button onClick={()=>moveCursor(1)} className="rounded-lg border px-3 py-2">→</button></div><h2 className="font-semibold">{rangeLabel(view,cursor)}</h2><div className="flex rounded-lg bg-slate-100 p-1">{(["day","week","month"] as CalendarView[]).map(x=><button key={x} onClick={()=>changeView(x)} className={`rounded-md px-3 py-1.5 text-sm capitalize ${view===x?"bg-white font-semibold shadow-sm":""}`}>{x}</button>)}</div></div>{view==="month"&&<div className="grid grid-cols-7 border-l border-t text-center text-xs font-semibold text-slate-500">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(x=><div className="border-b border-r py-2" key={x}>{x}</div>)}</div>}<div className={`grid ${view==="day"?"grid-cols-1":view==="week"?"grid-cols-7":"grid-cols-7"}`}>{days.map(day=><DayCell key={day.toISOString()} day={day} cursor={cursor} view={view} events={events.filter(x=>sameDay(new Date(x.startAt),day))} onDrop={drop}/>)}</div></section>
  <AlertsPanel alerts={alerts}/>{showForm&&<EventForm onClose={()=>setShowForm(false)} onSaved={async()=>{setShowForm(false);await load()}}/>}</main>
}

function DayCell({day,cursor,view,events,onDrop}:{day:Date;cursor:Date;view:CalendarView;events:CalendarEvent[];onDrop:(e:DragEvent,date:Date)=>void}){const outside=view==="month"&&day.getMonth()!==cursor.getMonth();return <div onDragOver={e=>e.preventDefault()} onDrop={e=>void onDrop(e,day)} className={`${view==="day"?"min-h-[520px]":view==="week"?"min-h-[520px]":"min-h-32"} border-b border-r p-1.5 ${outside?"bg-slate-50 text-slate-400":""}`}><p className="mb-1 text-xs font-semibold">{view==="day"?day.toLocaleDateString("en-GB",{weekday:"long",day:"numeric",month:"long"}):day.getDate()}</p><div className="space-y-1">{events.map(event=><EventChip event={event} key={event.id}/>)}</div></div>}
function EventChip({event}:{event:CalendarEvent}){const chip=<div draggable={event.reschedulable} onDragStart={e=>{e.dataTransfer.setData("calendar-id",event.id);e.dataTransfer.setData("calendar-start",event.startAt)}} title={`${event.entryType} · ${event.channel??"ERP"} · ${event.status}`} className={`rounded-md border-l-4 p-1.5 text-[11px] shadow-sm ${event.source==="META"?"border-blue-600 bg-blue-50":event.entryType==="DEAL_EXPIRY"?"border-rose-500 bg-rose-50":event.entryType==="CAMPAIGN"?"border-amber-500 bg-amber-50":"border-indigo-500 bg-indigo-50"}`}><p className="truncate font-semibold">{event.title}</p><p className="truncate text-slate-500">{event.allDay?"All day":new Date(event.startAt).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit"})} · {event.channel??event.entryType} · {event.status}</p><p className="font-medium text-slate-500">{event.source==="INTERNAL"?"ERP":event.source}{event.externalPublishStatus==="NOT_VERIFIED"?" · External not verified":""}</p></div>;return event.href?<Link href={event.href}>{chip}</Link>:chip}
function MetaCard({meta}:{meta:MetaStatus|null}){return <div className="min-w-64 rounded-2xl border bg-white p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Meta Business Suite</p><p className={`mt-1 font-bold ${meta?.status==="CONNECTED"?"text-emerald-700":meta?.status==="ERROR"?"text-red-700":"text-amber-700"}`}>{meta?.status?.replaceAll("_"," ")??"Unavailable"}</p><p className="mt-1 text-xs text-slate-500">Facebook {meta?.facebook?"✓":"—"} · Instagram {meta?.instagram?"✓":"—"}</p>{meta?.message&&<p className="mt-2 text-xs text-red-600">{meta.message}</p>}</div>}
function AlertsPanel({alerts}:{alerts:MarketingAlert[]}){return <section className="mt-5 rounded-2xl border bg-white p-5"><h2 className="font-semibold">Marketing alerts</h2>{alerts.length===0?<p className="mt-2 text-sm text-slate-500">No active alerts.</p>:<div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{alerts.map((x,i)=><div key={`${x.type}-${x.relatedEntityId}-${i}`} className={`rounded-xl p-3 text-sm ${x.severity==="URGENT"?"bg-red-50 text-red-800":x.severity==="WARNING"?"bg-amber-50 text-amber-900":"bg-blue-50 text-blue-800"}`}><p className="font-semibold">{x.title}</p><p className="mt-1 text-xs">{x.message}</p></div>)}</div>}</section>}
function EventForm({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const [error,setError]=useState("");async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);try{await apiFetch("/marketing/calendar",{method:"POST",body:JSON.stringify({title:fd.get("title"),description:fd.get("description"),entryType:fd.get("entryType"),startAt:new Date(String(fd.get("startAt"))).toISOString(),allDay:true})});onSaved()}catch(err){setError(err instanceof Error?err.message:"Unable to create event.")}}return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form onSubmit={e=>void submit(e)} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h2 className="text-xl font-semibold">Add planning event</h2><div className="mt-4 space-y-3"><input required name="title" placeholder="Event title" className="w-full rounded-lg border p-3"/><textarea name="description" placeholder="Description" className="w-full rounded-lg border p-3"/><select name="entryType" className="w-full rounded-lg border p-3"><option value="INTERNAL_EVENT">Internal event</option><option value="SEASONAL">Seasonal</option><option value="OTHER">Other</option></select><input required type="datetime-local" name="startAt" className="w-full rounded-lg border p-3"/></div>{error&&<p className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded-lg border px-4 py-2">Cancel</button><button className="rounded-lg bg-indigo-700 px-4 py-2 font-semibold text-white">Create event</button></div></form></div>}
function rangeFor(view:CalendarView,cursor:Date){if(view==="day")return{from:startDay(cursor),to:new Date(startDay(cursor).getTime()+dayMs-1)};if(view==="week"){const from=startDay(cursor);const iso=from.getDay()===0?7:from.getDay();from.setDate(from.getDate()-iso+1);return{from,to:new Date(from.getTime()+7*dayMs-1)}}const from=new Date(cursor.getFullYear(),cursor.getMonth(),1);const first=from.getDay()===0?7:from.getDay();from.setDate(from.getDate()-first+1);return{from,to:new Date(from.getTime()+42*dayMs-1)}}
function daysFor(view:CalendarView,from:Date,to:Date){const count=view==="day"?1:view==="week"?7:42;return Array.from({length:count},(_,i)=>new Date(from.getTime()+i*dayMs)).filter(x=>x<=to)}
function sameDay(a:Date,b:Date){return localDate(a)===localDate(b)}
function rangeLabel(view:CalendarView,cursor:Date){if(view==="month")return cursor.toLocaleDateString("en-GB",{month:"long",year:"numeric"});if(view==="day")return cursor.toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"});const r=rangeFor(view,cursor);return `${r.from.toLocaleDateString("en-GB",{day:"numeric",month:"short"})} – ${r.to.toLocaleDateString("en-GB",{day:"numeric",month:"short",year:"numeric"})}`}
