"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { ApiError, apiFetch } from "@/lib/api/client";
import type { DashboardResponse } from "@/types/dashboard";
import { useAuth } from "./auth-provider";

const labels: Record<string,string> = { liveNewLeads:"Live New Leads",activeLeads:"Active Leads",attentionLeads:"Attention Leads",callbacksDueToday:"Callbacks Due Today",missedCallbacks:"Missed Callbacks",quoting:"Quoting",goingToBook:"Going to Book",salesMade:"Sales Made",newSalesWaitingForAdmin:"New Sales",bookingsInProgress:"Bookings In Progress",operationsPending:"Operations Pending",supplierPending:"Supplier Pending",ticketingPending:"Ticketing Pending",actionRequired:"Action Required",travelStartingSoon:"Travel Soon",currentlyTravelling:"Currently Travelling",travelComplete:"Travel Complete",travelCompleteAccountsPending:"Travel Complete / Accounts Pending",tasksDue:"Tasks Due",reconciliationPending:"Reconciliation Pending",inReview:"In Review",discrepancies:"Discrepancies",reconciledToday:"Reconciled Today",activeEmployees:"Active Employees",presentToday:"Present Today",absentToday:"Absent Today",lateToday:"Late Today",onLeaveToday:"On Leave Today",pendingLeaveRequests:"Pending Leave Requests",openTickets:"Open IT Tickets",urgentTickets:"Urgent Tickets",ticketsInProgress:"Tickets In Progress",availableAssets:"Available Assets",assignedAssets:"Assigned Assets",assetsInRepair:"Assets In Repair",pendingAccessRequests:"Pending Access Requests" };
const links: Record<string,string> = { liveNewLeads:"/leads/live",activeLeads:"/leads/pipeline",attentionLeads:"/leads/attention",callbacksDueToday:"/leads/pipeline",missedCallbacks:"/leads/attention",quoting:"/leads/pipeline?status=QUOTING",goingToBook:"/leads/pipeline?status=GOING_TO_BOOK",salesMade:"/sales/submissions",newSalesWaitingForAdmin:"/admin/sales",bookingsInProgress:"/bookings",operationsPending:"/bookings?operationsStatus=PENDING",supplierPending:"/bookings?operationsStatus=SUPPLIER_PENDING",ticketingPending:"/bookings?operationsStatus=TICKETING_PENDING",actionRequired:"/bookings?operationsStatus=ACTION_REQUIRED",reconciliationPending:"/accounts/reconciliation",inReview:"/accounts/reconciliation",discrepancies:"/accounts/discrepancies",reconciledToday:"/accounts/reconciled",pendingLeaveRequests:"/hr/leave",openTickets:"/it/tickets",urgentTickets:"/it/tickets?priority=URGENT",availableAssets:"/it/assets",assignedAssets:"/it/assets?status=ASSIGNED",pendingAccessRequests:"/it/access-requests" };

export function RoleDashboard({ management = false }: { management?: boolean }) {
  const { user, hasPermission } = useAuth();
  const [data,setData]=useState<DashboardResponse|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [from,setFrom]=useState("");const [to,setTo]=useState("");
  const allowed=!management||hasPermission("dashboard.management.view");
  const load=useCallback(async()=>{if(!allowed)return;setLoading(true);setError("");const q=new URLSearchParams();if(from)q.set("dateFrom",from);if(to)q.set("dateTo",to);try{setData(await apiFetch<DashboardResponse>(`/dashboard${management?"/management":""}?${q}`));}catch(caught){setError(caught instanceof ApiError?caught.message:"Unable to load dashboard data.");}finally{setLoading(false);}},[allowed,from,management,to]);
  useEffect(()=>{void Promise.resolve().then(load);},[load]);
  if(!allowed)return <div className="mx-auto max-w-5xl p-8"><p className="rounded-2xl bg-amber-50 p-6 text-amber-900">You do not have permission to view the Management dashboard.</p></div>;
  function filter(e:FormEvent){e.preventDefault();void load();}
  return <div className="mx-auto max-w-7xl px-5 py-8 sm:px-8"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-wider text-cyan-700">Neo Tourism ERP</p><h1 className="mt-1 text-3xl font-semibold">{management?"Management Overview":`Welcome back, ${user?.firstName}`}</h1><p className="mt-2 text-sm text-slate-600">Live operational information from the ERP database.</p></div><form onSubmit={filter} className="flex flex-wrap gap-2"><input aria-label="Date from" type="date" value={from} onChange={e=>setFrom(e.target.value)} className="rounded-lg border p-2 text-sm"/><input aria-label="Date to" type="date" value={to} onChange={e=>setTo(e.target.value)} className="rounded-lg border p-2 text-sm"/><button className="rounded-lg bg-slate-900 px-4 text-sm font-semibold text-white">Apply</button></form></header>
    {loading&&<div className="mt-8 rounded-2xl border bg-white p-12 text-center text-slate-500">Loading dashboard…</div>}
    {!loading&&error&&<div className="mt-8 rounded-2xl border border-red-200 bg-red-50 p-8"><p className="font-semibold text-red-800">Dashboard unavailable</p><p className="mt-1 text-sm text-red-700">{error}</p><button onClick={()=>void load()} className="mt-4 text-sm font-semibold text-red-800">Try again</button></div>}
    {!loading&&!error&&data&&<><QuickActions hasPermission={hasPermission}/>{data.sales&&<Section title="Sales" color="cyan" kpis={data.sales.kpis}><div className="mt-5 grid gap-5 lg:grid-cols-2"><Breakdown title="Lead Pipeline" values={data.sales.pipeline}/><Breakdown title="Lead Ageing" values={data.sales.ageing}/></div><div className="mt-4 rounded-xl bg-cyan-50 p-4"><p className="text-sm text-cyan-900">Conversion rate</p><p className="text-3xl font-semibold text-cyan-950">{data.sales.conversion.conversionRate}%</p><p className="mt-1 text-xs text-cyan-800">{data.sales.conversion.definition}</p></div></Section>}{data.operations&&<Section title="Operations" color="emerald" kpis={data.operations.kpis}>{data.operations.upcomingTravel.length>0&&<div className="mt-5 overflow-x-auto"><h3 className="font-semibold">Upcoming travel</h3><table className="mt-2 min-w-full text-left text-sm"><thead><tr>{["Folder","Customer","Destination","Travel Start","Status","Owner"].map(h=><th className="border-b py-2 pr-4" key={h}>{h}</th>)}</tr></thead><tbody>{data.operations.upcomingTravel.map(x=><tr key={x.id}><td className="py-2 pr-4"><Link className="text-cyan-700" href={`/bookings/${x.id}`}>{x.folderNumber}</Link></td><td>{x.customer.firstName} {x.customer.lastName}</td><td>{x.destination}</td><td>{new Intl.DateTimeFormat("en-GB").format(new Date(x.travelStartDate))}</td><td>{x.operationsStatus}</td><td>{x.operationsOwner?`${x.operationsOwner.firstName} ${x.operationsOwner.lastName}`:"Unassigned"}</td></tr>)}</tbody></table></div>}</Section>}{data.accounts&&<Section title="Accounts" color="violet" kpis={data.accounts.kpis}>{data.accounts.financials&&<div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{data.accounts.financials.map(row=><div key={row.currency} className="rounded-xl bg-violet-50 p-4"><p className="font-semibold">{row.currency}</p><p className="mt-2 text-sm">Sales: {row.totalSalesValue.toLocaleString()}</p><p className="text-sm">Expected profit: {row.expectedProfit.toLocaleString()}</p><p className="text-sm">Passenger outstanding: {row.outstandingPassengerBalance.toLocaleString()}</p><p className="text-sm">Supplier outstanding: {row.outstandingSupplierBalance.toLocaleString()}</p></div>)}</div>}</Section>}{data.hr&&<Section title="HR" color="emerald" kpis={data.hr.kpis}/>} {data.it&&<Section title="IT" color="violet" kpis={data.it.kpis}/>}<Recent items={data.recentActivity}/>{data.recentNotifications&&<Notifications items={data.recentNotifications}/>} {!data.sales&&!data.operations&&!data.accounts&&!data.hr&&!data.it&&<p className="mt-8 rounded-2xl border bg-white p-8 text-slate-600">No dashboard sections are assigned to your role.</p>}</>}
  </div>;
}

function Section({title,kpis,children}:{title:string;kpis:Record<string,number>;children?:React.ReactNode;color:string}){return <section className="mt-8"><h2 className="text-lg font-semibold">{title}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(kpis).map(([key,value])=><Link href={links[key]??"/dashboard"} key={key} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm hover:border-cyan-300"><p className="text-sm text-slate-600">{labels[key]??humanize(key)}</p><p className="mt-2 text-3xl font-semibold">{value}</p></Link>)}</div>{children}</section>}
function Breakdown({title,values}:{title:string;values:Record<string,number>}){const max=Math.max(1,...Object.values(values));return <div className="rounded-2xl border bg-white p-5"><h3 className="font-semibold">{title}</h3><div className="mt-4 space-y-3">{Object.entries(values).map(([key,value])=><div key={key}><div className="flex justify-between text-xs"><span>{humanize(key)}</span><strong>{value}</strong></div><div className="mt-1 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-cyan-600" style={{width:`${value/max*100}%`}}/></div></div>)}</div></div>}
function QuickActions({hasPermission}:{hasPermission:(p:string)=>boolean}){const actions=[hasPermission("lead.assign")&&["Take New Lead","/leads/live"],hasPermission("customer.create")&&["Create Customer","/customers/new"],hasPermission("lead.attention.view")&&["Open Attention Leads","/leads/attention"],hasPermission("admin.sale_queue.view")&&["Open Admin Queue","/admin/sales"],hasPermission("finance.view")&&["Open Reconciliation Queue","/accounts/reconciliation"],hasPermission("hr.leave.create")&&["Request Leave","/hr/leave"],hasPermission("it.ticket.create")&&["Create IT Ticket","/it/tickets"]].filter(Boolean) as string[][];return actions.length?<div className="mt-7 flex flex-wrap gap-2">{actions.map(([label,href])=><Link key={label} href={href} className="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-semibold hover:bg-slate-50">{label}</Link>)}</div>:null;}
function Recent({items}:{items:DashboardResponse["recentActivity"]}){return <section className="mt-8 rounded-2xl border bg-white p-5"><h2 className="font-semibold">Recent activity</h2>{items.length?<ul className="mt-3 divide-y">{items.map(x=><li key={x.id} className="py-3 text-sm"><strong>{x.actorName}</strong> · {humanize(x.action)} <span className="text-slate-500">· {new Date(x.createdAt).toLocaleString("en-GB")}</span></li>)}</ul>:<p className="mt-3 text-sm text-slate-500">No recent activity for this view.</p>}</section>}
function Notifications({items}:{items:NonNullable<DashboardResponse["recentNotifications"]>}){return <section className="mt-8 rounded-2xl border bg-white p-5"><h2 className="font-semibold">Recent notifications</h2>{items.length?<ul className="mt-3 divide-y">{items.map(x=><li key={x.id} className="py-3 text-sm"><strong>{x.title}</strong><p className="text-slate-600">{x.message}</p></li>)}</ul>:<p className="mt-3 text-sm text-slate-500">No recent notifications.</p>}</section>}
function humanize(value:string){return value.replace(/([a-z])([A-Z])/g,"$1 $2").replaceAll("_"," ").toLowerCase().replace(/^./,x=>x.toUpperCase());}
